package com.mycompany.greenbasket;
import java.sql.*; import java.util.*;
public class UserRegDAO {
 public boolean saveUserReg(UserReg u){String q="INSERT INTO userreg(name,email,password,mob,gender,address,city,state) VALUES(?,?,?,?,?,?,?,?)";try(Connection c=DBConnection.getConnection();PreparedStatement p=c.prepareStatement(q,Statement.RETURN_GENERATED_KEYS)){p.setString(1,u.getName());p.setString(2,u.getEmail());p.setString(3,u.getPassword());p.setString(4,u.getMob());p.setString(5,u.getGender());p.setString(6,u.getAdd());p.setString(7,u.getCity());p.setString(8,u.getState());if(p.executeUpdate()>0){try(ResultSet r=p.getGeneratedKeys()){if(r.next())u.setId(r.getInt(1));}return true;}}catch(Exception e){e.printStackTrace();}return false;}
 public UserReg loginUser(String email,String password){String q="SELECT * FROM userreg WHERE email=? AND password=? LIMIT 1";try(Connection c=DBConnection.getConnection();PreparedStatement p=c.prepareStatement(q)){p.setString(1,email);p.setString(2,password);try(ResultSet r=p.executeQuery()){if(r.next())return map(r);}}catch(Exception e){e.printStackTrace();}return null;}
 public List<UserReg> getAllUsers(){List<UserReg> l=new ArrayList<>();try(Connection c=DBConnection.getConnection();PreparedStatement p=c.prepareStatement("SELECT * FROM userreg ORDER BY id DESC");ResultSet r=p.executeQuery()){while(r.next())l.add(map(r));}catch(Exception e){e.printStackTrace();}return l;}
 public UserReg getUserById(int id){try(Connection c=DBConnection.getConnection();PreparedStatement p=c.prepareStatement("SELECT * FROM userreg WHERE id=?")){p.setInt(1,id);try(ResultSet r=p.executeQuery()){if(r.next())return map(r);}}catch(Exception e){e.printStackTrace();}return null;}
 public boolean updateUser(UserReg u){String q="UPDATE userreg SET name=?,email=?,password=?,mob=?,gender=?,address=?,city=?,state=? WHERE id=?";try(Connection c=DBConnection.getConnection();PreparedStatement p=c.prepareStatement(q)){p.setString(1,u.getName());p.setString(2,u.getEmail());p.setString(3,u.getPassword());p.setString(4,u.getMob());p.setString(5,u.getGender());p.setString(6,u.getAdd());p.setString(7,u.getCity());p.setString(8,u.getState());p.setInt(9,u.getId());return p.executeUpdate()>0;}catch(Exception e){e.printStackTrace();return false;}}
 public boolean deleteUser(int id){try(Connection c=DBConnection.getConnection();PreparedStatement p=c.prepareStatement("DELETE FROM userreg WHERE id=?")){p.setInt(1,id);return p.executeUpdate()>0;}catch(Exception e){e.printStackTrace();return false;}}
 private UserReg map(ResultSet r)throws SQLException{UserReg u=new UserReg();u.setId(r.getInt("id"));u.setName(r.getString("name"));u.setEmail(r.getString("email"));u.setPassword(r.getString("password"));u.setMob(r.getString("mob"));u.setGender(r.getString("gender"));u.setAdd(r.getString("address"));u.setCity(r.getString("city"));u.setState(r.getString("state"));return u;}
}
