<%@ page contentType="text/html; charset=UTF-8" pageEncoding="UTF-8" %>
<%@ page import="java.util.*,java.net.URLEncoder,com.mycompany.greenbasket.*" %>
<%
ProductDAO homeDao=new ProductDAO();
List<Category> homeCats=homeDao.getCategories();
List<Product> homeProducts=homeDao.getAllActive(null,null);
int featuredCount=Math.min(6,homeProducts.size());
Map<Integer,String[]> homeRatings=new FeedbackDAO().getRatingSummary();
%>
<!DOCTYPE html><html lang="en"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>GreenBasket | Organic Marketplace</title><link rel="stylesheet" href="<%=request.getContextPath()%>/assets/css/greenbasket.css"></head><body>
<%@ include file="/WEB-INF/includes/header.jspf" %>
<section class="hero"><div class="container hero-grid"><div><span class="eyebrow">🌱 From verified local farms</span><h1>Good food begins with a <span>trusted farm.</span></h1><p>Shop fresh organic produce directly from farmers, discover where your food comes from, and support cleaner farming with every basket.</p><div class="hero-actions"><a class="btn btn-primary" href="<%=ctx%>/products.jsp">Explore the market →</a><a class="btn btn-outline" href="<%=ctx%>/FarmerRegistration.jsp">Sell your harvest</a></div><div class="trust-row"><div class="trust"><i>✓</i> Farmer-first marketplace</div><div class="trust"><i>🌿</i> Organic-only catalog</div><div class="trust"><i>📍</i> Local discovery</div></div></div><div class="hero-visual"><div class="produce-orb"></div><div class="produce-card produce-main"><div class="verified-badge">✓ VERIFIED FARMER</div><div class="emoji">🥬</div><strong>Harvested fresh, listed directly by growers.</strong><p style="margin:6px 0 0;color:#6b776f;font-size:13px">No noisy marketplace. Just clear product, price and farm details.</p></div><div class="produce-card mini-card"><span class="emoji">🍅</span><div><strong>Seasonal picks</strong><div style="font-size:12px;color:#68756d">Fresh this week</div></div></div><div class="produce-card verified-card"><strong style="color:#123d2a">Farm to basket</strong><div style="font-size:12px;color:#68756d">Simple • Transparent • Local</div></div></div></div></section>
<section class="section section-white"><div class="container"><div class="section-head"><div><span class="eyebrow">Shop by category</span><h2 style="margin-top:14px">The organic pantry, thoughtfully organized.</h2><p>GreenBasket is organic by default, so categories focus on what shoppers actually need.</p></div><a class="btn btn-outline" href="<%=ctx%>/products.jsp">View all products</a></div><div class="category-grid"><% for(Category c:homeCats){ %><a class="category-card" href="<%=ctx%>/products.jsp?category=<%=c.getId()%>"><div class="category-icon"><%=c.getIcon()%></div><strong><%=c.getName()%></strong></a><% } %></div></div></section>
<section class="section"><div class="container"><div class="section-head"><div><span class="eyebrow">Fresh in the marketplace</span><h2 style="margin-top:14px">Farm picks ready for your basket.</h2><p>A curated first look at products from GreenBasket farmers across the organic pantry.</p></div><a class="btn btn-outline" href="<%=ctx%>/products.jsp">Shop full catalog →</a></div>
<% if(featuredCount>0){ %><div class="products-grid">
<% for(int i=0;i<featuredCount;i++){ Product p=homeProducts.get(i); String st=homeDao.verificationStatus(p.getFarmerId()); String[] hr=homeRatings.get(p.getId()); String hs=ProductImageUtil.resolveForWeb(request.getContextPath(),p.getImageUrl(),p.getName(),p.getCategoryName()); String hfb=ProductImageUtil.localFallbackForWeb(request.getContextPath(),p.getName(),p.getCategoryName()); %>
<article class="product-card"><a class="product-media" href="<%=ctx%>/products.jsp?q=<%=URLEncoder.encode(p.getName(),"UTF-8")%>"><img src="<%=hs%>" alt="<%=p.getName()%>" loading="lazy" data-local-fallback="<%=hfb%>" onerror="greenBasketImageFallback(this)"></a><div class="product-body"><div class="product-meta"><span><%=p.getCategoryName()%></span><span><%=p.getStock()%> <%=p.getUnit()%> available</span></div><h3><%=p.getName()%></h3><%if(hr!=null){%><div class="product-rating"><span class="rating-stars">★★★★★</span><strong><%=hr[0]%></strong><span>(<%=hr[1]%>)</span></div><%}%><p><%=p.getDescription()%></p><div style="margin-bottom:12px;font-size:12px;color:#53665a"><strong><%=p.getFarmName()%></strong> <%if("APPROVED".equals(st)){%><span class="verified-inline"> ✓ Verified</span><%}%></div><div class="price-row"><div class="price">₹<%=p.getPrice()%> <small>/ <%=p.getUnit()%></small></div><a class="btn btn-soft" href="<%=ctx%>/products.jsp?q=<%=URLEncoder.encode(p.getName(),"UTF-8")%>">View</a></div></div></article>
<% } %></div><% } %></div></section>
<section class="section"><div class="container"><div class="section-head"><div><span class="eyebrow">Built around trust</span><h2 style="margin-top:14px">A marketplace that feels human.</h2></div></div><div class="feature-grid"><article class="feature-card"><div class="feature-num">01</div><h3>Know your farmer</h3><p>Every product is tied to a real farmer profile and farm identity, so buying feels transparent rather than anonymous.</p></article><article class="feature-card"><div class="feature-num">02</div><h3>Simple organic discovery</h3><p>Filter by focused organic categories and find relevant products without clutter or unrelated listings.</p></article><article class="feature-card"><div class="feature-num">03</div><h3>Designed for both sides</h3><p>Buyers get a polished store experience while farmers get a focused seller studio for managing products and verification.</p></article></div></div></section>
<section class="section section-white"><div class="container"><div class="cta-strip"><div><h2>Growing organic produce?</h2><p>Create your farmer profile, submit verification and list your harvest on GreenBasket.</p></div><a class="btn btn-gold" href="<%=ctx%>/FarmerRegistration.jsp">Start selling →</a></div></div></section>
<script>function greenBasketImageFallback(img){img.onerror=null;if(img.dataset.localFallback && img.src!==img.dataset.localFallback){img.src=img.dataset.localFallback;}}</script><%@ include file="/WEB-INF/includes/footer.jspf" %></body></html>
